#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ $# -eq 0 ]; then
    exec "$script_dir""/hrc-out"
    exit 1
fi

code=$("$script_dir""/hrc-out" "$@")
if [[ "$code" != "" ]]; then
   exec lua "-" <<< "$code"
fi
